# Generated by Django 2.2.6 on 2020-07-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Writer',
        ),
    ]
