# Generated by Django 2.2.6 on 2020-07-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200716_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writer',
            new_name='Author',
        ),
    ]
