# Generated by Django 2.2.14 on 2020-07-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
